name: macOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@v1.14.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
