name: macOS

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        swift: [
          "5",
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift @ ${{ matrix.swift}}
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
    - name: Status Check Success
      if: ${{ success() }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'macOS / unit tests'
        description: 'Unit tests on macOS succeeded'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
    - name: Status Check Failure
      if: ${{ failure() }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'macOS / unit tests'
        description: 'Unit tests on macOS failed'
        state: 'failure'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
  add_pending_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Pending Status Check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'macOS / unit tests'
          description: 'Running unit tests on macOS'
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
