name: ubuntu

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: fwal/setup-swift@v1.14.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Status Check Success
      if: ${{ success() }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'ubuntu / unit tests'
        description: 'Unit tests on ubuntu succeeded'
        state: 'success'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
    - name: Status Check Failure
      if: ${{ failure() }}
      uses: Sibz/github-status-action@v1
      with:
        authToken: ${{secrets.GITHUB_TOKEN}}
        context: 'ubuntu / unit tests'
        description: 'Unit tests on ubuntu failed'
        state: 'failure'
        sha: ${{github.event.pull_request.head.sha || github.sha}}
  add_pending_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Pending Status Check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'ubuntu / unit tests'
          description: 'Running unit tests on ubuntu'
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
